import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Thomas Koefod (image header graphic goes here)
        </h1>

        <p className={styles.description}>tagline goes here</p>
        <div> nav bar </div>
        <div>main content</div>
        <div>feature component</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="http://thomaskoefod.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by by Thomas Koefod
        </a>
      </footer>
    </div>
  );
}
